version: '3'
services:
  python3:
    env_file: .env
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/
    ports:
      - "9000:8080"
